"""
src/nl2sql/schema.py

정형 데이터 8개 테이블의 스키마를 LLM 프롬프트에 삽입 가능한 텍스트로 정리한다.
(document_chunks는 벡터 검색 전용 테이블이라 NL2SQL 스키마 컨텍스트에서 제외)
"""

SCHEMA_TEXT = """\
## 테이블: departments (부서, 6행)
- id (PK, 정수)
- name (부서명, 예: "경영지원팀", "클라우드사업부")
- head_id (부서장 직원 id, employees.id 참조)
- created_at (생성일시)

## 테이블: employees (직원, 45행)
- id (PK, 정수)
- name (직원 이름)
- email (이메일)
- position (직급, 예: "부장", "이사", "사원")
- dept_id (소속 부서 id, departments.id 참조)
- hire_date (입사일)
- salary (연봉, 정수 원화)
- is_active (재직 여부, boolean)
- created_at (생성일시)

## 테이블: clients (고객사, 30행)
- id (PK, 정수)
- name (고객사명, 예: "Client-A")
- industry (업종, 예: "제조업", "금융", "의료/바이오")
- region (지역, 예: "서울", "경기", "대전")
- company_size (기업 규모, 예: "startup", "mid")
- contact_name (담당자 이름)
- contact_email (담당자 이메일)
- registered_at (고객사 등록일)
- is_active (거래 활성 여부, boolean)
- created_at (생성일시)

## 테이블: products (제품/솔루션, 12행)
- id (PK, 정수)
- name (제품명, 예: "Product-C1")
- category (카테고리, 예: "cloud", "security", "data", "consulting")
- description (제품 설명)
- price_monthly (월 구독료, 정수 원화)
- version (버전)
- release_date (출시일)
- status (제품 상태, 예: "active")
- created_at (생성일시)

## 테이블: contracts (계약, 65행)
- id (PK, 정수)
- client_id (고객사 id, clients.id 참조)
- product_id (제품 id, products.id 참조)
- manager_id (담당 직원 id, employees.id 참조)
- contract_type (계약 유형)
- amount (계약 금액, 정수 원화)
- start_date (계약 시작일)
- end_date (계약 종료일, NULL 가능)
- status (계약 상태, 예: "active")
- created_at (생성일시)

## 테이블: projects (프로젝트, 40행)
- id (PK, 정수)
- name (프로젝트명)
- client_id (고객사 id, clients.id 참조)
- manager_id (담당 직원 id, employees.id 참조)
- contract_id (연관 계약 id, contracts.id 참조, NULL 가능)
- status (진행 상태, 예: "in_progress", "completed")
- start_date (시작일)
- end_date (종료일, NULL 가능)
- budget (예산, 정수 원화)
- description (프로젝트 설명)
- created_at (생성일시)

## 테이블: sales (매출, 500행)
- id (PK, 정수)
- contract_id (계약 id, contracts.id 참조)
- client_id (고객사 id, clients.id 참조)
- product_id (제품 id, products.id 참조)
- amount (매출액, 정수 원화)
- sale_date (매출 발생일)
- quarter (분기, 예: "2025-Q3" 형식의 문자열)
- category (제품 카테고리, products.category와 동일한 값 범위)
- region (매출 발생 지역)
- created_at (생성일시)

## 테이블: support_tickets (기술 지원 티켓, 120행)
- id (PK, 정수)
- client_id (고객사 id, clients.id 참조)
- product_id (제품 id, products.id 참조)
- assignee_id (담당 직원 id, employees.id 참조, NULL 가능)
- title (티켓 제목)
- description (상세 내용)
- priority (우선순위, 예: "critical", "high", "medium", "low")
- status (처리 상태, 예: "open", "in_progress", "resolved")
- created_at (티켓 생성일시)
- resolved_at (해결일시, NULL 가능)
"""